version: "3.8"
services:
  database:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: films
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@localhost.net
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - internal
    depends_on:
      - database
  backend:
    image: "ghcr.io/${OWNER}/nest_films_backend:latest"
    build: ./backend
    environment:
      PORT: 3000
      DATABASE_DRIVER: "postgres"
      DATABASE_URL: "postgres://database:5432/films"
      DATABASE_USERNAME: ${DB_USER}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    networks:
      - internal
    depends_on:
      database:
        condition: service_healthy
  frontend:
    image: "ghcr.io/${OWNER}/nest_films_frontend:latest"
    build: ./frontend
    volumes:
      - frontend_build:/app/dist
    networks:
      - internal
    environment:
      VITE_BASE_URL: /
      VITE_API_URL: /api/afisha
      VITE_CDN_URL: /content/afisha
  server:
    image: "ghcr.io/${OWNER}/nest_films_server:latest"
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - frontend_build:/var/www
    depends_on:
      - frontend
      - backend
    networks:
      - internal

volumes:
  db_data:
  pgadmin-data:
  frontend_build:

networks:
  internal:
